feat: add elastic search handlers
edly-io/forum pull request #65
Opened 2024-08-26 12:18 UTC by Ali-Salman29

- Add elastic search handlers on create, update, and delete methods
- Updated temporary indexes to fetch recent aliases from the elastic search

2024-08-26 15:39 UTC, Faraz32123 commented on forum/handlers.py
> +from forum.search.es_helper import ElasticsearchHelper
import order

2024-08-26 16:01 UTC, Ali-Salman29 commented on forum/handlers.py
> +from forum.search.es_helper import ElasticsearchHelper
Could you please elaborate?

2024-08-26 17:25 UTC, Faraz32123 commented on forum/handlers.py
> +from forum.search.es_helper import ElasticsearchHelper
```
+from forum.search.es_helper import ElasticsearchHelper
 from forum.utils import get_str_value_from_collection
-from forum.search.es_helper import ElasticsearchHelper
```

2024-08-26 19:31 UTC, taimoor-ahmed-1 requested changes

2024-08-27 09:21 UTC, Faraz32123 commented on forum/utils.py
> +        raise ValueError(f"No signal found for name: {name}")
we can make a dict and return a matched value
```
signals_map = {
        "comment_deleted": signals.comment_deleted,
        "comment_thread_deleted": signals.comment_thread_deleted,
        "comment_inserted": signals.comment_inserted,
        "comment_thread_inserted": signals.comment_thread_inserted,
        "comment_updated": signals.comment_updated,
        "comment_thread_updated": signals.comment_thread_updated,
    }

    try:
        return signals_map[name]
    except KeyError:
        raise ValueError(f"No signal found for name: {name}")
```

2024-08-27 09:35 UTC, Faraz32123 approved these changes
LGTM!

2024-08-27 09:46 UTC, taimoor-ahmed-1 approved these changes

2024-08-27 11:50 UTC, merged